services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: avinash
      POSTGRES_PASSWORD: Avinash123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
